# Generated by Django 4.0.3 on 2022-03-11 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterpiece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_id', to=settings.AUTH_USER_MODEL)),
                ('masterpiece_id', models.ForeignKey(db_column='masterpiece_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterpiece.masterpiece')),
                ('seller_id', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
