# Generated by Django 3.2.12 on 2022-03-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_id', to='user.user')),
                ('seller_id', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_id', to='user.user')),
            ],
        ),
    ]
