# Generated by Django 3.2.12 on 2022-03-11 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterpiece', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='masterpiece_id',
            field=models.ForeignKey(db_column='masterpiece_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterpiece.masterpiece'),
        ),
    ]
