# Generated by Django 4.0.3 on 2022-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
