# Generated by Django 3.2.12 on 2022-04-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_field',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
