# Generated by Django 3.2.12 on 2022-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220413_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_year',
            new_name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
