# Generated by Django 3.2.12 on 2022-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220426_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.ImageField(default=None, upload_to='card'),
        ),
    ]
