# Generated by Django 4.0.3 on 2022-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='thumnail/')),
                ('exhibition_comment', models.TextField()),
                ('exhibition_start', models.DateTimeField()),
                ('exhibition_end', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
