# Generated by Django 3.2.12 on 2022-03-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibition', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('masterpiece_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='masterpieces/')),
                ('comment', models.TextField()),
                ('price', models.IntegerField()),
                ('trade_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibition_id', models.ForeignKey(db_column='exhibition_id', on_delete=django.db.models.deletion.CASCADE, to='exhibition.exhibition')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
