# Generated by Django 4.0.3 on 2022-03-11 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('masterpiece_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Annoymous', max_length=50)),
                ('image', models.ImageField(upload_to='masterpieces/')),
                ('comment', models.TextField()),
                ('price', models.IntegerField()),
                ('trade_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibition_id', models.ForeignKey(db_column='exhibition_id', on_delete=django.db.models.deletion.CASCADE, to='exhibition.exhibition')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
