# Generated by Django 3.2.12 on 2022-03-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpiece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpiece',
            name='name',
            field=models.CharField(default='Annoymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='trade_status',
            field=models.BooleanField(default=False),
        ),
    ]
