# Generated by Django 3.2.12 on 2022-03-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('pdf', models.FileField(upload_to=pdf.models.pdf_path)),
                ('img_length', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
