# Generated by Django 3.2.12 on 2022-03-23 15:59

from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('pdf', models.FileField(upload_to=pdf.models.pdf_path)),
                ('img_length', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
