# Generated by Django 3.2.12 on 2022-04-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_pdfmodel_upload_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='deadline',
            field=models.DateField(default=None),
        ),
    ]
