# Generated by Django 3.2.12 on 2022-04-15 08:28

from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_pdfmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='pdf',
            field=models.FileField(upload_to=pdf.models.pdf_path),
        ),
    ]
