# Generated by Django 3.2.12 on 2022-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_remove_pdfmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
