# Generated by Django 3.2.12 on 2022-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_pdfmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='img_path',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='job_field',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
