# Generated by Django 4.0.3 on 2022-04-01 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0003_alter_pdfmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyetracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('rating_time', models.TimeField()),
                ('coordinate', models.TextField()),
                ('owner_id', models.ForeignKey(db_column='owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('pdf_fk', models.ForeignKey(db_column='pdf_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_fk', to='pdf.pdfmodel')),
                ('user_id', models.ForeignKey(db_column='rater', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
