# Generated by Django 4.0.3 on 2022-03-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyetracking',
            name='owner_id',
        ),
    ]
