# Generated by Django 3.2.12 on 2022-04-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cs',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
