# Generated by Django 3.2.12 on 2022-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_rename_phone_cs_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='category',
            field=models.CharField(default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='cs',
            name='isFAQ',
            field=models.BooleanField(default=None),
        ),
    ]
